name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "~/conftask/app.env"
        FILE_DATA: "$DB_CONFIG"

    - name: Test
      run: go test -v ./...
