name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Set up test credentials
      run: sudo touch ~/conftask/app.env && sudo echo DB_NAME=$DB_NAME > ~/conftask/app.env && sudo echo DB_HOST=$DB_HOST >> ~/conftask/app.env && sudo echo DB_USER=$DB_USER >> ~/conftask/app.env && sudo echo DB_PASSWORD=$DB_PASSWORD >> ~/conftask/app.env

    - name: Test
      run: go test -v ./...
