name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - uses: 1arp/create-a-file-action@0.2
        with:
          path: '~/conftask'
          file: 'app.env'
          content: |
            $DB_CONFIG

    - name: Test
      run: go test -v ./...
