name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -o bin/task-amd64.exe ./...

    - name: Test
      run: go test -v ./...

    - uses: actions/upload-artifact@v3
      with:
        name: task
        path: bin/task-amd64.exe