name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Set up test credentials
      run: mkdir ~/conftask && touch ~/conftask/app.env && echo $DB_CONFIG >> ~/conftask/app.env && cat ~/conftask/app.env

    - name: Test
      run: go test -v ./...
